language: python
python:
 - 3.6
sudo: false
before_install:
  - export GOPATH=$HOME/golang
  - export PATH=$PATH:$GOPATH/bin
install:
  - eval "$(gimme 1.7)"
  - go get github.com/ValeLint/vale
  - pip install -r requirements.txt
script:
  - tox -e $TOX_ENV
cache:
  directories:
    - $HOME/www/.tox
