language: python
python:
 - 2.7
sudo: false
env:
 - TOX_ENV=docs
before_install:
  - export GOPATH=$HOME/golang
  - export PATH=$PATH:$GOPATH/bin
install:
 - pip install tox
 - eval "$(gimme 1.7)"
 - go get github.com/jdkato/vale
script:
 - vale docs/
 - tox -e $TOX_ENV
