site_name: Write the Docs
theme_dir: theme
pages:
  - ['index.md', 'Write the Docs']
  - ['conf/index.md', 'Conference']
  - ['conf/na/2015.md', 'Conference', '2015 North America']
  - ['meetups.md', 'Meetups']
