site_name: Write the Docs
theme_dir: theme
pages:
  - ['index.md', 'Write the Docs']
  - ['code-of-conduct.md', 'Code of Conduct']
  - ['code-of-conduct-response.md', 'Code of Conduct Response Guide']
  - ['news/announcing-2015.md', 'Announcing Write the Docs 2015 NA']
  - ['news/cfp-ticket-prices.md', 'Announcing Call for Proposals and Ticket Prices']
  - ['news/announcing-keynotes-sponsors-reminder.md', 'Announcing Keynotes, Initial Sponsors, and a Reminder']
  - ['news/announcing-presentations.md', 'Conferences', 'Announcing Presentations']
  - ['conf/index.md', 'Conferences']
  - ['conf/na/2015.md', 'Conferences', 'North America 2015']
  - ['conf/na/cfp.md', 'Conferences', 'Call for Proposals - North America 2015']
  - ['conf/na/2015/speakers.md', 'Conferences', 'Speakers - North America 2015']
  - ['conf/na/2015/visiting.md', 'Conferences', 'Visiting Portland - North America 2015']
  - ['conf/na/2015/hike.md', 'Conferences', 'Hike - North America 2015']
  - ['conf/na/2015/writing-day.md', 'Conferences', 'Writing Day - North America 2015']
  - ['conf/na/2015/unconference.md', 'Conferences', 'Unconference - North America 2015']
  - ['conf/na/2015/speaking.md', 'Conferences', 'Speakers Guide - North America 2015']
  - ['conf/na/2015/schedule.md', 'Conferences', 'Schedule - North America 2015']
  - ['conf/na/2015/lightning-talks.md', 'Conferences', 'Lightning Talks - North America 2015']
  - ['conf/na/2015/news/more-conference-details.md', 'Conferences', 'More Conference Details - North America 2015']
  - ['conf/na/2015/news/conference-sold-out-schedule-party.md', 'Conferences', 'Conference sells out, Party Venue, and Schedule Details - North America 2015']
  - ['conf/na/2015/news/welcome-to-write-the-docs.md', 'Conferences', 'Welcome to Write the Docs - North America 2015']
  - ['conf/na/2015/news/thanks-for-coming.md', 'Conferences', 'Thanks for coming  - North America 2015']
  - ['conf/eu/2015.md', 'Conferences', 'Europe 2015']
  - ['conf/eu/2015/cfp.md', 'Conferences', 'Call for Proposals - Europe 2015']
  - ['conf/eu/2015/visiting.md', 'Conferences', 'Visiting Prague - Europe 2015']
  - ['conf/eu/2015/news/announcing-eu-2015.md', 'Announcing Write the Docs 2015 EU']
  - ['meetups.md', 'Meetups']
  - ['guide/documentarian.md', 'Documentarian']
