site_name: Write the Docs
theme_dir: theme
pages:
  - ['index.md', 'Write the Docs']
  - ['code-of-conduct.md', 'Code of Conduct']
  - ['news/announcing-2015.md', 'Announcing Write the Docs 2015 NA']
  - ['news/cfp-ticket-prices.md', 'Announcing Call for Proposals and Ticket Prices']
  - ['news/announcing-keynotes-sponsors-reminder.md', 'Announcing Keynotes, Initial Sponsors, and a Reminder']
  - ['conf/index.md', 'Conferences']
  - ['conf/na/2015.md', 'Conferences', 'North America 2015']
  - ['conf/na/cfp.md', 'Conferences', 'Call for Proposals - North America 2015']
  - ['conf/na/2015/speakers.md', 'Conferences', 'Speakers - North America 2015']
  - ['conf/na/2015/visiting.md', 'Visiting Portland', 'Visiting Portland - North America 2015']
  - ['meetups.md', 'Meetups']
