name: Cincinatti
shortcode: cincinatti # prague australia?
templatecode: cin # HACK
year: 2018
city: Cincinatti
area: Ohio
tz: EST
email: support@writethedocs.org
short_dates: "Aug X-Y, 2018"

tickets:
  community:
    price: $250
  corporate:
    price: $100
  independent:
    price: $50
  student:
    price: $25

sponsorship:
  first_draft:
    price: $250
  second_draft:
    price: $500
  publisher:
    price: $1000
  patron:
    price: $2000
  job_fair:
    price: $500
    half: $250
  lanyard:
    price: TBD
  writing_day:
    price: TBD

date: # how do we handle these? human readable would be nice.
  main: "**August X-Y, 2018, in Cincinatti, Ohio**"
  tickets_live: "May 2018"
  month: August
  day_one:
    event: Talks
    date: X
    summary: The primary conference day, with talks.
  day_two:
    event: Discussions
    date: X
    summary: Talk with other documentarians to learn more about everything and anything.
  day_three:
    event: Sprints
    date: X
    summary: Get some work done and learn by doing from the others in the room

about:
  summary:
    "The main presentation track takes place from **September 9-11 (Monday and Tuesday) from 10:00 to 18:00**.
    During the main event we also run an :doc:`/conf/prague/2018/unconference`.

    You can find out more information about the venue and its accessibility on our :doc:`/conf/prague/2018/venue` page."
  venue:
    "Beer Place"
  attendees: 100
  mainroom:
    Main Ballroom
  unconfroom:
    Unconference Room

cfp:
  url: https://goo.gl/forms/M6YjhBgmCEwOwrzP2
  ends: Tuesday, May 15th
  notification: Thursday, May 31st

job_fair:
  location: Unconference Room, downstairs

flaglanding: True
flagspeakersannounced: False
flagcfp: False
flagticketsonsale: False
flaghashike: False
flaghasboat: False
