name: Portland

shortcode: prague # prague australia?
templatecode: eu # HACK
year: 2018
city: Prague
area: European
tz: CEST
email: prague@writethedocs.org

tickets:
  community:
    price: FIXME
  corporate:
    price: FIXME
  independent:
    price: FIXME
  student:
    price: FIXME

date: # how do we handle these? human readable would be nice.
  main: "**September 9-11, 2018, in Prague, Czechia**"
  tickets_live: "January 2018"
  month: May
  sat: 5

about:
  summary:
    "The main presentation track takes place from **September 9-11 (Monday and Tuesday) from 10:00 to 18:00**.
    During the main event we also run an :doc:`/conf/portland/2018/unconference`.

    You can find out more information about the venue and its accessibility on our :doc:`/conf/prague/2018/venue` page."
  location:
    "TBA"

cfp:
  url: FIXME
  ends: FIXME
  notification: FIXME


flagspeakersannounced: False
flagcfp: False
flagticketsonsale: False
flaghashike: False
flaghasboat: True
