name: Australia

shortcode: australia # prague australia?
year: 2018
city: Melbourne
area: Australia
area_adj: Australian
tz: AEST

tickets:
  corporate:
    price: 100
    url: 
  independent:
    price: 75
    url:
  student:
    price: 50
    url:

date: # how do we handle these? human readable would be nice.
  main: "**November 15-16, 2018, in Melbourne, Australia**"
  short:
  tickets_live: "July 2018"
  month: November
  sat: 


about:
  summary:
  location:

cfp:
  url: 
  ends: 
  notification: 

flagspeakersannounced: False
flagcfp: False
flagticketsonsale: False
flaghashike: False
flaghasboat: False
